[tool.poetry]
name = "simpletuner"
version = "0.1.0"
description = "Stable Diffusion 2.x and XL tuner."
authors = ["bghira"]
license = "SUL"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = "^2.4.1"
torchaudio = {version = "*", source = "pytorch-rocm"}
torchmetrics = {version = "^1", source = "pytorch-rocm"}
torchvision = {version = "*", source = "pytorch-rocm"}
pytorch-triton-rocm = {version = "*", source = "pytorch-rocm"}
accelerate = "^0.34.0"
boto3 = "^1"
botocore = "^1"
clip-interrogator = "^0.6"
colorama = "^0.4"
compel = "^2"
dadaptation = "^3"
datasets = "^2"
deepspeed = "^0.14"
diffusers = "0.30.0"
iterutils = "^0.1"
numpy = "^1"
open-clip-torch = "^2"
opencv-python = "^4"
pandas = "^2"
peft = "^0.12"
pillow = "^10"
prodigyopt = "^1"
requests = "^2"
safetensors = "^0.4"
scipy = "^1"
tensorboard = "^2.17.1"
torchsde = "^0.2"
transformers = "^4"
urllib3 = "<1.27"
wandb = "^0.17.8"
sentencepiece = "^0.2.0"
optimum-quanto = {git = "https://github.com/bghira/optimum-quanto-simpletuner", rev = "simpletuner/lora-resume"}
lycoris-lora = {git = "https://github.com/kohakublueleaf/lycoris", rev = "dev"}
torch-optimi = "^0.2.1"
fastapi = "^0.112.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
priority = "explicit"
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.0"